"""empty message

Revision ID: 9c0d951bfedf
Revises: 
Create Date: 2019-04-30 13:29:09.303115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0d951bfedf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post', sa.String(), nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'post')
    # ### end Alembic commands ###
